import Link from "next/link";

export const metadata = { title: "Methodology · Devclass" };

export default function MethodologyPage() {
  return (
    <main className="min-h-screen px-6 py-16 max-w-3xl mx-auto">
      <Link href="/" className="text-xs font-mono text-parchment-600 hover:text-gold tracking-widest">
        &larr; DEVCLASS
      </Link>

      <h1 className="font-display text-5xl text-parchment-100 mt-8 mb-4">Methodology</h1>
      <p className="text-parchment-600 italic">
        How Devclass turns 33 questions into one of ten archetypes &mdash; and what we are
        deliberately not claiming about it.
      </p>

      <div className="rune-divider my-10" />

      <article className="prose-devclass space-y-8 text-parchment-200 leading-relaxed">
        <section>
          <h2 className="font-display text-2xl text-gold-bright">The honest framing</h2>
          <p>
            Devclass is a <em>self-reflection instrument</em>, not a personality test. It has not
            been validated against external behavioral outcomes, has no test-retest reliability
            study, and its constructs were chosen for descriptive utility, not statistical
            independence. Treat it the way you'd treat a thoughtful coffee with a senior engineer:
            useful for noticing yourself, useless as a measurement.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-gold-bright">The nine pillars</h2>
          <p>
            We chose nine because each one names a distinct mode of failure in real engineers we
            and our reviewers had worked with. They are intentionally non-orthogonal &mdash;
            Engineering Integrity correlates with Critical Skepticism in most people, and that's
            fine. The point is descriptive coverage, not factor purity:
          </p>
          <ul className="list-disc pl-6 space-y-1 text-sm">
            <li><strong>ANL</strong> &mdash; Analytical Decomposition: breaking problems before solving them.</li>
            <li><strong>CRT</strong> &mdash; Critical Skepticism: defaulting to "show me the failure mode".</li>
            <li><strong>CRE</strong> &mdash; Creative Synthesis: combining unfamiliar ideas into new structure.</li>
            <li><strong>DOM</strong> &mdash; Domain Mastery: knowing the layer below the one you work at.</li>
            <li><strong>FOC</strong> &mdash; Focused Persistence: finishing the boring 80%.</li>
            <li><strong>CUR</strong> &mdash; Cultivated Curiosity: learning beyond what's required.</li>
            <li><strong>INT</strong> &mdash; Engineering Integrity: writing what you actually believe is right.</li>
            <li><strong>REG</strong> &mdash; Self-Regulation: the loop between feeling and acting.</li>
            <li><strong>COM</strong> &mdash; Communicative Clarity: making the invisible legible.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-2xl text-gold-bright">The scoring</h2>
          <p>
            Each Likert item contributes a signed value (-25 to +25) on its target pillar. Reverse-
            scored items invert this. Behavioral and forced-choice items carry hand-tuned multi-
            metric deltas (each option can contribute to 1&ndash;3 pillars at once, including
            negatively). Raw scores are clamped to &plusmn;60 and linearly remapped to a 0&ndash;100
            scale centered at 50.
          </p>
          <p>
            Each archetype has a fixed reference vector in the same nine-dimensional space. Class
            assignment is by cosine similarity. If your top-2 archetypes are within 1.5% of each
            other (cosine ratio &ge; 0.985), we call you multiclass and surface both.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-gold-bright">The plan generation</h2>
          <p>
            Your four-week plan is generated by Google's <code>gemini-2.5-flash</code> with your
            full vector, archetype name, and three weakest pillars as context. The model is asked
            for real, well-known references only and to write in the voice that suits your
            archetype. It will sometimes hallucinate book titles &mdash; if you don't recognize one,
            assume the model invented it.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-gold-bright">What this is built on</h2>
          <p>The work that most directly shaped Devclass:</p>
          <ul className="list-disc pl-6 space-y-2 text-sm">
            <li>
              <strong>Manware</strong>, &ldquo;Are You A Good Programmer?&rdquo; (May 2026) &mdash;
              the catalyst question.
            </li>
            <li>
              <strong>John Ousterhout</strong>, <em>A Philosophy of Software Design</em> &mdash;
              the framing of complexity as the central problem.
            </li>
            <li>
              <strong>Hunt &amp; Thomas</strong>, <em>The Pragmatic Programmer</em> &mdash; the
              working definition of <em>care</em>.
            </li>
            <li>
              <strong>Martin Kleppmann</strong>, <em>Designing Data-Intensive Applications</em>
              &mdash; what mature Domain Mastery looks like.
            </li>
            <li>
              <strong>Peter Naur</strong>, &ldquo;Programming as Theory Building&rdquo; (1985) &mdash;
              why integrity and communication are inseparable.
            </li>
            <li>
              <strong>Fred Brooks</strong>, &ldquo;No Silver Bullet&rdquo; (1986) &mdash; the
              calibration check.
            </li>
            <li>
              <strong>Costa &amp; McCrae</strong> Big Five literature &mdash; for the vector-space
              classification machinery, adapted (not validated) here.
            </li>
            <li>
              <strong>Robert Nystrom</strong>, <em>Crafting Interpreters</em> &mdash; for the
              standard of what generous technical writing looks like.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-2xl text-gold-bright">What's coming</h2>
          <p>
            After deployment we will add optional GitHub OAuth. With your permission, we'll read
            public commit cadence, language diversity, and PR comment patterns to <em>complement</em>
            (never replace) your self-reported answers. You'll always be able to take the quiz
            entirely as a guest.
          </p>
        </section>

        <p className="italic text-parchment-600 text-sm pt-8 border-t border-parchment-800/40">
          Built in the open by{" "}
          <a className="text-gold underline" href="https://github.com/FediMechergui/devclass">
            FediMechergui/devclass
          </a>
          . Corrections welcome &mdash; especially on the pillars themselves.
        </p>
      </article>
    </main>
  );
}
